    swagger: "2.0"
    info:
      title: "Rack app"
      description: "Sample Rack application."
      version: "1.0.0"
    host: "rack-app-api.endpoints.YOUR-PROJECT-ID.cloud.goog"
    schemes:
      - "http"
    paths:
      /:
        get:
          description: "Root path."
          operationId: "root"
          responses:
            200:
              description: "Success."
              schema:
                type: string
            400:
              description: "Bad data."
      "/hello":
        get:
          description: "Hello world."
          operationId: "hello"
          responses:
            200:
              description: "Success."
              schema:
                type: string
            400:
              description: "Bad data."
          security:
            - api_key: []
    securityDefinitions:
      api_key:
        type: "apiKey"
        name: "key"
        in: "query"
